<template>
  <div>
    <h1 class="title">
      General Welcome – Chief Investment Officer of PM Capital (Investment Manager)
    </h1>
    <b-message>
      <h4>
        VIDEO FROM THE INVESTMENT MANAGER - To be provided
      </h4>
    </b-message>
    <div class="space"></div>
    <p>
      Australians love to travel. We live a long way from the most populous parts of the world, but it’s not unusual that when
      landing in a foreign city we bump into an Australian or two. Given our outward focus and desire to experience the best
      the world can offer, it still surprises me that Australians keep such a large proportion of their assets in Australian
      equities rather than global equities.
    </p>
    <p>
      We all know Australia is a fantastic place to live and historically its markets have generated good long term returns. However,
      to say that Australia’s narrowly focused equity market, representing approximately 2% of global market capitalisation,
      can produce all of the best investment opportunities would be wrong.
    </p>
    <p>
      Lately, it’s been a particularly exciting time to be investing in global equities, with recent returns from international
      markets demonstrably stronger than returns from the Australian market. In fact, global equity markets have outperformed
      the Australian share market in four out of the five past years, with Australia’s lack of diversity outside banks and
      miners hindering returns.
    </p>
    <p>
      In such an environment, PM Capital GO 2025 provides an efficient and flexible way to take advantage of what PM Capital sees
      as the best the world can offer for long term investors. GO 2025, with a first of its kind redeemable Listed Investment
      Company (LIC) offer known as PTrackERS, gives investors more choice and control when it comes to how they hold and
      realise their LIC investments.
    </p>
    <p>
      PTrackERS are a real step forward for LICs in Australia, providing a fairer structure for shareholders looking to create
      wealth over the long term. It’s a genuine and exciting advancement, so I encourage you to read the letter from GO 2025’s
      Chairman Andrew McGill, and the Prospectus for more information.
    </p>
    <p>
      PTrackERS are a joint offering by PM Capital Global Opportunities Fund (ASX Ticker: PGF) and GO 2025. When PGF listed in
      December 2013, its aim was to give shareholders access to what we saw as significantly better opportunities in international
      markets than in Australia. Between the IPO and 31 May 2018, we’ve delivered on this aim. We’ve generated a 75% total
      return on PGF’s portfolio before tax and after fees and expenses, compared to a 45% return generated by the S&P ASX
      200 Accumulation Index. We continue to see a better breadth of opportunities in offshore markets relative to Australia.
    </p>
    <p>
      I'm very pleased that PM Capital is the investment manager for GO 2025. We believe our benchmark-unaware philosophy and process,
      tested over 20 years and executed by one of the most experienced global equities teams in Australia, suits GO 2025’s
      aims and structure, allowing us to continue to find market anomalies that can provide attractive long term returns.
      Our Insights section on the PM Capital website (www.pmcapital.com.au/insights) may give you a better understanding
      of why and how we buy stocks and manage the portfolio.
    </p>
    <p>
      Our long term track record is attractive. Since its inception our longest-running global equities fund (the PM Capital Global
      Companies Fund (ARSN 092 434 618)) to 31 May 2018 has produced a return of 439.7% against an Index return of 137.3%
      - an outperformance of 302.4%. This means that an investment of $100,000 at inception would now be worth $539,703,
      which is $302,400 more than if it was invested in the Index.
    </p>
    <p>
      The PM Capital team has significant personal investments in the funds and listed investment companies that we manage, so
      we see investors in GO 2025 as our co-investors, investing together to access a subset of global opportunities off
      the radar of most other managers. As at May 2018, PM Capital and its staff held 8.9% of PGF. We see it as very important
      that we communicate with our co-investors on investment matters, so please don’t hesitate to contact us. If you have
      any questions about GO 2025 please contact your financial adviser, or alternately PM Capital’s GO 2025 team on +612
      8243 0888, or by email on Go2025@pmcapital.com.au.
    </p>
    <p>
      My team and I are passionate about creating returns via our experience, our patience and conviction. We are looking forward
      to doing the same for investors in GO 2025.
    </p>
    <br>
    <p>
      Yours sincerely
    </p>
    <p>
      <strong>PM Capital Limited</strong>
    </p>
    <br>
    <br>
    <p>
      Paul Moore
      <br> Chairman and Chief Investment Officer
    </p>
  </div>
</template>

<script>
export default {

}
</script>

<style lang="scss" scoped>

</style>

